<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Unlocker</AssemblyName>
    <RootNamespace>Unlocker</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Unlocker.ico</ApplicationIcon>
    <AssemblyTitle>Unlocker</AssemblyTitle>
    <Description>Unlocker - 强制删除或解除占用被占用的文件和文件夹</Description>
    <Version>1.0.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationDefaultFont>Microsoft YaHei UI, 9f</ApplicationDefaultFont>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

</Project>
